# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20150818_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='es_activo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_centralita',
            new_name='es_centralita',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_company',
            new_name='es_coordinador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_coordinador',
            new_name='es_empresa',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_homologado',
            new_name='es_homologado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='es_superusuario',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_usuario',
            new_name='es_syva',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_worker',
            new_name='es_trabajador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='useranexoparque',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='useranexotrobajo',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usercentral',
            old_name='plant',
            new_name='planta',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='activity',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='contact',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='mobile',
            new_name='movil',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='name',
            new_name='nombre_empresa',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='subcontrate',
            new_name='subcontratado',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='userdepartment',
            old_name='departament',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='notETT',
            new_name='noETT',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='protection',
            new_name='proteccion',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='risk',
            new_name='riesgo',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='safe',
            new_name='seguridad',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='EPI_date',
            new_name='EPI_fecha',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='TA2_date',
            new_name='TA2_fecha',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='formation_date',
            new_name='fecha_formacion',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='information',
            new_name='informacion',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='information_doc',
            new_name='informacion_doc',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='medical',
            new_name='medica',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='medical_doc',
            new_name='medica_doc',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='skill_doc',
            new_name='trabajo_doc',
        ),
    ]
