# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20150818_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_centralita',
            new_name='is_centralita',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_coordinador',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_empresa',
            new_name='is_coordinador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_homologado',
            new_name='is_usuario',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_syva',
            new_name='is_worker',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apellidos',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usuario',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='useranexoparque',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useranexotrobajo',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercentral',
            old_name='planta',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='actividad',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='contacto',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='movil',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='nombre_empresa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='subcontratado',
            new_name='subcontrate',
        ),
        migrations.RenameField(
            model_name='userdepartment',
            old_name='departamento',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='noETT',
            new_name='notETT',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='proteccion',
            new_name='protection',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='riesgo',
            new_name='risk',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='seguridad',
            new_name='safe',
        ),
        migrations.RenameField(
            model_name='userdocs',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='EPI_fecha',
            new_name='EPI_date',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='TA2_fecha',
            new_name='TA2_date',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='fecha_formacion',
            new_name='formation_date',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='informacion',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='informacion_doc',
            new_name='information_doc',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='medica',
            new_name='medical',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='medica_doc',
            new_name='medical_doc',
        ),
        migrations.RenameField(
            model_name='userworkers',
            old_name='trabajo_doc',
            new_name='skill_doc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='es_trabajador',
        ),
    ]
